sonar.projectKey=AnderssonProgramming_state-machine-bridge-test
sonar.organization=anderssonprogramming

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__init__.py,frontend/node_modules/**,frontend/dist/**